// The DECLARED judgments of the Gate 2 T-S2 interpolation sweep (sweep-interpolations.mjs): every
// interpolation the mechanical rules cannot classify, matched by file, enclosing top-level declaration and
// an expression pattern, with the class it was judged and why. A judgment that matches nothing is reported
// STALE, so this list cannot silently outlive the code it describes.
export const JUDGED = [];
const J = JUDGED;
const j = (file, fn, re, cls, why) => J.push({ file: file === "conductor.mjs" ? "scripts/conductor.mjs" : `scripts/lib/${file}`, fn, re, class: cls, why });
const ALL = /.*/;

// ── line-sink flow: every value reaches a `L.map(escapeControls)` / `md.map(escapeControls)` / `lines.map(escapeControls)` join
j("briefing.mjs", "buildBrief", ALL, "sink-flow", "every line is pushed onto L, joined through L.map(escapeControls) at buildBrief's return");
j("briefing.mjs", "BRIEF_REMEDIES", ALL, "sink-flow", "each render() result is pushed onto buildBrief's L (briefRemedy) or its trackerLines, which join L's sink; ids in commands go through printedId/asCode");
j("render.mjs", "render", ALL, "sink-flow", "every PROJECT.md line is pushed onto md, joined through md.map(escapeControls); cells additionally through tableRow's escapeTableCell");
j("render.mjs", "tableRow", /^cells\.map\(escapeTableCell\)\.join\(" \| "\)$/, "escaped", "each cell through escapeTableCell");
j("render.mjs", "normalizeForDiffSummary", ALL, "not-output", "slices PROJECT.md text for a diff comparison; prints nothing");
j("integrity.mjs", "CHECKS", ALL, "sink-flow", "every finding detail is printed only by formatIntegrity(), whose L joins through L.map(escapeControls); runIntegrity's sole caller is integrity(). Ids in commands go through printedId/orNoRemedy/asCode/commandValue, and the secondary tracker's shellQuote(t.repo) is reached only when CONTROL_CHARACTER.test(t.repo) is false");
j("integrity.mjs", "recordedShas", ALL, "sink-flow", "`where` labels (gate1/gate2 + engine key) feed CHECKS details only");
j("integrity.mjs", "integrity", ALL, "escaped", "formatIntegrity() returns the sink-joined report");
j("rules.mjs", "rulesBlock", ALL, "sink-flow", "the managed block's lines join through lines.map(escapeControls)");
for (const fn of ["closedItemStep", "gateProcedureLines", "intakeLines", "inwardListStep", "registrationStep", "reportingLines", "watermarkStep", "pmCmd"]) {
  j("rules.mjs", fn, ALL, "sink-flow", "a rules-block line builder: its only consumer is rulesBlock()'s lines (pmCmd also names a platform-vocabulary command prefix)");
}
j("constants.mjs", "mirroredEpicIdPrefix", ALL, "sink-flow", "used only by rules.mjs registrationStep, inside the rules block sink; the scope is slugged");
j("rules.mjs", "secondaryTrackerKey", ALL, "not-output", "a match key for upsert/remove; never printed");
j("rules.mjs", "writeRules", ALL, "engine", "`name` is the rules file basename from PLATFORM_RULES_CHAIN, `platform` a validated vocabulary value; `block` is rulesBlock()'s sink-joined text written to the file");
j("rules.mjs", "rulesBlockAmbiguousMessage", ALL, "engine", "shown is the engine's own rules file path relative to ROOT; marker line numbers and kinds are engine-derived");
j("rules.mjs", "rulesBlockArrangement", ALL, "engine", "the engine's own rules file path");
j("releases.mjs", "releaseShow", /^(rel\.id|rel\.intent|a\.via|a\.was)$/, "sink-flow", "pushed onto out, printed through out.map(escapeControls)");
j("claims.mjs", "owners", /^formatOwners\(rows\)$/, "escaped", "formatOwners() returns its L through L.map(escapeControls)");
j("claims.mjs", "owners", /^JSON\.stringify/, "json", "--json: the whole stdout is one JSON document");
j("verify-specs.mjs", "danglingBlock", ALL, "sink-flow", "spread into verify-specs' L, joined through L.map(escapeControls)");
j("verify-specs.mjs", "verifySpecs", ALL, "escaped", "formatHeaderCandidates/formatSpecCoverage return sink-joined text");
j("activity-report.mjs", "activity", /^formatReport\(/, "escaped", "formatReport() returns its L through L.map(escapeControls)");
j("activity-report.mjs", "activity", /^JSON\.stringify/, "json", "--json: one JSON document");
j("activity-report.mjs", "activity", /^e\.message$/, "passthrough", "a StateUnreadableError: its reason is escaped where readStateFile() builds it");
j("activity-report.mjs", "hrs", ALL, "engine", "a number");
j("dependency-order.mjs", "dependencyNotes", ALL, "sink-flow", "notes are printed only by render() (md) and buildBrief() (L), both line sinks");
j("dependency-order.mjs", "blockedWithoutDependsOnNote", ALL, "sink-flow", "a BRIEF_REMEDIES entry and a dependencyNotes() note — brief and PROJECT.md sinks only; its command's id goes through printedId");
j("epic-progress.mjs", "bar", ALL, "sink-flow", "bar() is called only by render() and buildBrief(), both line sinks");
j("epic-progress.mjs", "orderQueueWithDependencies", ALL, "sink-flow", "its notes are printed only by buildBrief()'s L");
j("active-pointer.mjs", "staleMarker", ALL, "engine", "a day count; staleMarker() feeds render/brief sinks");
j("constants.mjs", "gateSummary", ALL, "sink-flow", "called only by gateTableRows(), printed only by render() and buildBrief()");
j("archive-gate.mjs", "gateTableRows", ALL, "sink-flow", "rows printed only by render() and buildBrief()");
j("cross-spec-review.mjs", "crossSpecLine", ALL, "sink-flow", "printed only by render(), buildBrief() and releaseShow()'s out — all line sinks");
j("disposition.mjs", "correctionMarking", ALL, "sink-flow", "printed only by render() and buildBrief()");
j("disposition.mjs", "correctionNote", ALL, "sink-flow", "printed only by render() and buildBrief()");
j("constants.mjs", "releaseLine", /^s\.members$/, "engine", "a count (its id is escaped)");
j("links.mjs", "epicReferences", ALL, "sink-flow", "`where` labels are printed by integrity (sink) and by remove-epic, which escapes its citation (Gate 2 T-S2) and the stripped-holder list");
j("constants.mjs", "withdrawnGate", ALL, "engine", "a gate number");

// ── engine-composed: numbers, registry and vocabulary values, validated values, engine paths/versions/shas
j("conductor.mjs", "showEngineBanner", /^(path\.dirname\(fileURLToPath\(import\.meta\.url\)\)|pluginVersion\(\) \|\| "unknown"|platform)$/, "engine", "the engine's own install directory and shipped version; a validated platform");
j("conductor.mjs", "showEngineBanner", /^rulesTarget\(/, "justified", "rules-target prints ONE machine-read path (evals/observe.py opens it); escaping would name a different file. It is the rules file under the harness's CLAUDE_PROJECT_DIR");
j("conductor.mjs", "helpAt", /^verdict\.message$/, "passthrough", "an argv-surface refusal, whose caller tokens are escaped where it is built");
j("activity-log.mjs", "setActivityLog", ALL, "engine", "arg is validated on|off before this line; activityDir() is the engine's log directory under ROOT");
j("activity-log.mjs", "segmentName", ALL, "not-output", "a segment file name");
j("activity-log.mjs", "diffEvents", ALL, "not-output", "an event field of a JSON-lines activity segment");
j("add-epic.mjs", "addEpic", /^(EPIC_ID_FORMAT\.source|lane|status)$/, "engine", "the id-format regex source; lane and status are validated against KNOWN_LANES/KNOWN_STATUSES before");
j("add-epic.mjs", "addEpic", /^(e\.message|perr)$/, "passthrough", "parseStoryFlags / parseLinkFlags / parentError messages, each escaping the values it quotes where it is built");
j("add-epic.mjs", "planHierarchy", /^JSON\.stringify\(plan\)$/, "json", "the plan is one JSON document");
j("add-epic.mjs", "requireFlagValues", ALL, "passthrough", "valuelessFlagError()'s message: registry flag names, the token quoted by flagInValuePositionMessage");
j("add-epic.mjs", "valuelessFlagError", ALL, "engine", "registry flag names and requirement text");
j("constants.mjs", "flagInValuePositionMessage", ALL, "engine", "registry flag name and requirement text (the token is escaped)");
j("add-many.mjs", "addMany", /^(EPIC_ID_FORMAT\.source|allowedKeys\.join\(", "\)|k)$/, "engine", "the id-format source and the batch key allowlist; k is filtered to allowedKeys before");
j("add-many.mjs", "addMany", /^msg$/, "passthrough", "die(): every caller escapes the values it quotes");
j("archive-gate.mjs", "blockedDelivered", ALL, "passthrough", "o.detail is a DELIVERED_OBLIGATIONS detail, escaped where it is built");
j("archive-gate.mjs", "DELIVERED_OBLIGATIONS", /^(esc\(staleness\.headSha\)|summary\.claimed|summary\.outstanding)$/, "escaped", "esc() is escapeControls over String(v); the rest are counts");
j("archive-gate.mjs", "deliveredArchiveInvocation", ALL, "engine", "carry flags from obligationArchiveFlags(): engine placeholders");
j("archive-gate.mjs", "dispositionInvocation", ALL, "engine", "AGENT_OUTCOMES vocabulary, the engine template, engine carry placeholders, and echoed tokens that echoedTokens() shell-quoted after replacing any control-character value with a placeholder");
j("archive-gate.mjs", "gateRemedy", ALL, "engine", "base/head are engine placeholders (`<sha>`, REPLACING constants)");
j("archive-gate.mjs", "outstandingSummary", ALL, "engine", "counts");
j("archive-gate.mjs", "archiveGate", /^(invalid|cerr|refusal|lines\[\d\]|gate2Failure\.detail|handoffFailure\.detail|named|remedy)$/, "passthrough", "dispositionError/correctionError messages (escaped), the escaped refusal prefix, asCode() remedy lines, escaped obligation details, the escaped story list and engine remedy prose");
j("archive-gate.mjs", "archiveGate", /^(outcomeOf\(epic\)|i\.n)$/, "engine", "outcomeOf() answers from KNOWN_OUTCOMES or `unknown`; a story number");
j("argv-surface.mjs", "checkCommandLine", ALL, "engine", "the dispatched verb (VERB_POSITIONALS has a row for it) and a DECLARED flag name");
j("argv-surface.mjs", "surplusMessage", ALL, "engine", "verb, registry arity form, and a declared flag's name (undeclared flags are refused first)");
j("argv-surface.mjs", "undeclaredFlagMessage", ALL, "engine", "verb, registry flag list and positional form; the caller tokens are escaped");
j("changelog.mjs", "changelog", ALL, "engine", "sections of the plugin's own shipped CHANGELOG.md (design D0)");
j("claims.mjs", "claim", ALL, "engine", "claimExpiry() is an ISO string computed from a parsed date, or null");
j("claims.mjs", "refuseHeld", /^claimExpiry\(claim\)$/, "engine", "a computed ISO string");
j("claims.mjs", "refuseHeld", /^(verb|what)$/, "passthrough", "callers pass literal verbs and `this repository` or an escaped epic id");
j("claims.mjs", "die", ALL, "passthrough", "every caller escapes the values it quotes");
j("claims.mjs", "writeRepoClaim", ALL, "not-output", "a temporary file name");
j("commit-watch.mjs", "beginObservation", ALL, "not-output", "the observation file body and its temporary name");
j("commit-watch.mjs", "observeLockPaths", ALL, "not-output", "a lock path");
j("constants.mjs", "asCode", ALL, "passthrough", "a builder result whose own values were swept where it was built");
j("constants.mjs", "escapeControls", ALL, "engine", "the escaper's own hex digits");
j("constants.mjs", "noRemedyMessage", ALL, "engine", "kind is the literal epic|release");
j("constants.mjs", "printedId", ALL, "engine", "kind is the literal epic|release");
j("constants.mjs", "unstorableSkipLine", ALL, "engine", "kind is a literal (change|plan|archive directory)");
j("constants.mjs", "shellQuote", ALL, "justified", "the quoter itself; every printing caller is judged at its own site");
j("constants.mjs", "warnDetachedTree", ALL, "engine", "a git tag name (git refuses control characters in ref names) and a literal");
j("created-at.mjs", "idNeedle", ALL, "not-output", "a git -S search needle");
j("created-at.mjs", "recoverCreatedAt", ALL, "engine", "counts");
j("cross-spec-review.mjs", "releaseSpecFiles", ALL, "not-output", "a Map key; record-cross-spec-review prints only the spec COUNT");
j("detour-stack.mjs", "die", ALL, "passthrough", "every caller escapes the values it quotes");
j("detour-stack.mjs", "pushDetour", /^(pushReport|note)$/, "passthrough", "the escaped save report, and deferralNote() which escapes the detour ids (Gate 2 T-I5)");
j("detour-stack.mjs", "popDetour", /^owed\.map|^\[\.\.\.new Set\(targets\.map\(d => orNoRemedy/, "escaped", "each id through escapeControls; each command through orNoRemedy/printedId");
j("detour-stack.mjs", "popDetour", /^detourId$/, "escaped", "appendHonchoMemory → honchoMemoryLine() escapes it (design D7)");
j("disposition.mjs", "storyDispositionError", ALL, "engine", "the only caller passes the literal `wont-do` past the vocabulary check");
j("gate-guard.mjs", "setGateGuard", ALL, "engine", "val is validated on|off; out holds engine lines and escaped ids");
j("git.mjs", "commitsNotReachedBy", ALL, "not-output", "a cache key of full object names");
j("git.mjs", "differsFromHead", ALL, "not-output", "a git argument");
j("git.mjs", "unresolvedCommitsMessage", ALL, "engine", "flags is a literal flag list passed by each caller; the values are escaped");
j("help.mjs", "flagLine", ALL, "engine", "flag registry rows");
j("help.mjs", "verbHelp", ALL, "engine", "flag and positional registries, POSITIONAL_USAGE, epicBatchKeys()");
j("lane-routing.mjs", "suggestLane", ALL, "json", "one JSON document");
j("triage.mjs", "triage", ALL, "json", "one JSON document");
j("unconsidered.mjs", "unconsideredOutcomesReport", ALL, "json", "one JSON document");
j("worktree-hygiene.mjs", "changesets", ALL, "json", "one JSON document");
j("worktree-hygiene.mjs", "verifyWorktrees", ALL, "json", "one JSON document; the branch-derived epic id is a JSON string");
j("lessons.mjs", "adviceText", ALL, "escaped", "body is built from escapeControls(rule) and escapeControls(file)");
j("links.mjs", "ordinal", ALL, "engine", "a number and its suffix");
j("links.mjs", "unknownLinkTypeMessage", ALL, "engine", "the link-type registry (the caller values are escaped)");
j("purge-logs.mjs", "die", ALL, "passthrough", "every caller passes a literal or a vocabulary list");
j("purge-logs.mjs", "purgeLogs", ALL, "engine", "kind validated against PURGE_KINDS, a byte count, an engine log kind");
j("refusal.mjs", "refusalFor", ALL, "passthrough", "conflict messages hold revision numbers and engine lock paths; unreadableStateMessage() carries a reason escaped where readStateFile() builds it");
j("releases.mjs", "die", ALL, "passthrough", "every caller escapes the values it quotes");
j("remove-epic.mjs", "epicSummaryTable", ALL, "escaped", "escapeControls(...) then padding/slicing");
j("save-report.mjs", "reportSave", ALL, "passthrough", "each caller's changed/unchanged line is swept at the caller");
j("self-hosting.mjs", "delegateToCheckout", ALL, "engine", "a spawn error of the node binary; the target path is escaped");
j("state.mjs", "describeHolder", ALL, "engine", "an integer pid and an engine holder kind (host and time are escaped)");
j("state.mjs", "lockRefusalMessage", ALL, "engine", "revision numbers, stale seconds and the engine's own lock paths relative to the project directory");
j("state.mjs", "persistFailure", ALL, "engine", "revision numbers");
j("state.mjs", "revisionOfText", ALL, "engine", "an engine reason string");
j("state.mjs", "saveState", ALL, "not-output", "the state file body, a temporary name, and a revision number in an engine message");
j("state.mjs", "seedCreationFields", ALL, "engine", "StateConflictError/StatePersistError constructors: revision numbers, an engine verb name and an engine-composed reason");
j("state.mjs", "shapeProblem", ALL, "engine", "an array index");
j("state.mjs", "unreadableStateMessage", ALL, "passthrough", "StateUnreadableError message: an engine display path and a reason escaped where readStateFile() builds it");
j("subcommands.mjs", "appendHonchoMemory", ALL, "escaped", "honchoMemoryLine() escapes the epic id and reason (design D7)");
j("subcommands.mjs", "changedFiles", ALL, "not-output", "a git path list");
j("subcommands.mjs", "looksLikeUnloggedMinimalDetour", ALL, "not-output", "a substring test against a commit subject");
j("subcommands.mjs", "ownArtifacts", ALL, "not-output", "an artifact path compared against changed files");
j("subcommands.mjs", "retractDetour", /^(commits\.join\(", "\)|label)$/, "engine", "detours.log row shas, filtered to hexadecimal by rowShasOverlap(), or git's short sha");
j("subcommands.mjs", "retractDetour", /^msg$/, "passthrough", "refuse(): every caller escapes the values it quotes");
j("tracker-refresh-writeback.mjs", "recordTrackerRefresh", ALL, "engine", "verdict validated against the refresh verdict vocabulary before");
j("update-epic.mjs", "missingGateWithdrawals", ALL, "not-output", "a state key");
j("write-conflicts.mjs", "recordConflict", ALL, "engine", "one log line: an engine verb name and two revision numbers");

// ── mixed functions, per expression
j("migrations.mjs", "upgrade", /^(running|newest)$/, "engine", "plugin versions of the running and installed engine");
j("migrations.mjs", "upgrade", /^(applied|state\.pmVersion \|\| "unknown"|rewritten\.join\(" "\))$/, "engine", "a count; pmVersion AFTER stampVersion() wrote the running engine's version; engine-known file names");
j("migrations.mjs", "upgrade", /^delta\.map\(s => s\.body\)\.join\("\\n\\n"\)$/, "engine", "sections of the shipped CHANGELOG.md");
j("migrations.mjs", "upgrade", /^l$/, "escaped", "openspecCurrencyLines() returns its lines escaped (Gate 2 T-S2)");
j("rank.mjs", "reorder", /^msg$/, "passthrough", "fail(): every caller escapes the values it quotes");
j("reconciler-writeback.mjs", "recordReconcile", /^(why|owedPhrase)$/, "passthrough", "refuse(): every caller escapes; owedPhrase is built from escaped ids");
j("releases.mjs", "epicReasonPair", ALL, "engine", "flagName is the literal unmember|undefer");
j("releases.mjs", "release", /^(EPIC_ID_FORMAT\.source|reasonFlags\.join\(" and --"\)|reasonFlags\[0\]|one\.flag|others\[0\]\.flag)$/, "engine", "the id-format source and literal flag names");
j("releases.mjs", "release", /^derr$/, "passthrough", "an epicReasonPair() refusal, escaped where built");
j("releases.mjs", "release", /^printedId\((unmember|undefer)\.epic\) && (unmember|undefer)\.epic$/, "escaped", "printedId() throws the no-remedy signal on a control character, so the raw id is reached only without one (Gate 2 T-S2)");
j("releases.mjs", "release", /^releaseLine\(/, "escaped", "releaseLine() escapes the release id (Gate 2 T-I3); the rest are counts");
j("remove-epic.mjs", "removeEpic", /^(epicSummaryTable\(|cite\((frames|owed)\)|\[\.\.\.toRemove\]\.map)/, "escaped", "the summary table escapes each cell; cite() escapes its whole citation (Gate 2 T-S2); each id through escapeControls");
j("remove-epic.mjs", "removeEpic", /^\[\.\.\.new Set\(owed\.map\(r => orNoRemedy/, "escaped", "each command through orNoRemedy/printedId");
j("remove-epic.mjs", "removeEpic", /^(flag|how)$/, "engine", "a literal flag name and engine wording");
j("subcommands.mjs", "supersedeAmended", ALL, "engine", "reflog object names and git short shas; the reason is `amended into <sha>`; commands through orNoRemedy/printedId; ids escaped");
j("subcommands.mjs", "attributionNudge", ALL, "engine", "full commit object names from the observation, engine exclusion prose, and commands through asCode/orNoRemedy/printedId");
j("subcommands.mjs", "runNudge", ALL, "engine", "git short shas, detours.log row shas written by the engine, and engine sentences built from them");
j("subcommands.mjs", "sync", /^(claim\.label|added)$/, "engine", "a literal artifact label and a count");
j("subcommands.mjs", "sync", /^backfilled\.join\(", "\)$/, "engine", "backfilled ids passed STORABLE_EPIC_ID (no control character) before registration");
j("subcommands.mjs", "honchoMemory", /^e\.message$/, "passthrough", "honchoMemoryLine()/appendHonchoMemory refusals, escaped where built");
j("subcommands.mjs", "honchoMemory", /^note$/, "escaped", "deferralNote() escapes the detour ids (Gate 2 T-I5)");
j("gate-review-writeback.mjs", "recordGateReview", ALL, "engine", "literal flag names, full object names resolved by git (unresolved values are refused first) and a validated gate number");
j("tracker.mjs", "setTracker", /^(flag|field|kept)$/, "engine", "a literal flag or field name and a direction from KNOWN_TRACKER_DIRECTIONS");
j("tracker.mjs", "setTracker", /^line$/, "passthrough", "notices built with escapeControls");
j("update-epic.mjs", "echoedTokens", ALL, "engine", "flag names are DECLARED (argv-surface refuses others first); values are shell-quoted only when they hold no control character, else REENTER_PLACEHOLDER");
j("update-epic.mjs", "regressionRefusal", /^(quoted\(i\.(reason|title)\)|o\.items\.map\(i => `(withdrawal reason|story))/, "escaped", "quoted() is escapeControls(JSON.stringify(...))");
j("update-epic.mjs", "regressionRefusal", /^(i\.n|named|status|\[\.\.\.new Set\(reenter\)\]\.join\(", "\)|invocation|findings|remedies)$/, "engine", "a story number; the escaped findings list; a validated status; declared flag names; dispositionInvocation()'s engine command or no-remedy prose; asCode() remedy lines");
j("update-epic.mjs", "updateEpic", /^(linkTypeVocabulary\(\)|twice|g|gate|n|colons|k|declared\.setOnly|r\.flag|r\.key|row\.flag|row\.clearNote|contradictory\.join\(", --(clear )?"\)|supplied\.map\(k => `--\$\{k\}`\)\.join\(", "\)|nullableRows\.map\(r => `\$\{r\.flag\} \(\$\{r\.key\}\)`\)\.join\(", "\)|stillThere\.join\(", "\)|notLanded\.join\(", gate "\))$/, "engine", "registry vocabularies and flag rows, validated gate numbers, story indices and colon counts, declared flag names, and resolved full commit names");
j("update-epic.mjs", "updateEpic", /^(perr|e\.message|err|verdict\.message)$/, "passthrough", "parentError / parseLinkFlags / parseStoryFlags / storyDispositionError / archiveGate messages, each escaping what it quotes where it is built");

j("remove-epic.mjs", "removeEpic", /^\(owed\.length \?/, "passthrough", "a conditional `+` chain whose non-literal operands (the escaped citation, the orNoRemedy command list) are each swept where they sit");

