// scripts/lib/render.mjs
// Renders PROJECT.md from state.json + on-disk truth. Circular with
// lib/active-pointer.mjs (staleMarker), lib/autonomy.mjs (getAutonomy), and
// lib/add-epic.mjs (parseFlags) -- see the design doc.

import fs from "node:fs";
import { loadState, saveState, readJSON } from "./state.mjs";
import { reconcileArchived, resolveEpics, bar, missing } from "./epic-progress.mjs";
import { buildBrief } from "./briefing.mjs";
import { staleMarker } from "./active-pointer.mjs";
import { getAutonomy } from "./autonomy.mjs";
import { parseFlags } from "./add-epic.mjs";
import { validLink } from "./links.mjs";
import { DETOURS_LOG, PROJECT_MD, STATE_PATH, RENDER_STAMP_PATH, CONDUCTOR_DIR } from "./constants.mjs";

export function render() {
  const state = loadState();
  if (reconcileArchived(state)) saveState(state);
  const epics = resolveEpics(state);
  const md = [];

  md.push("# PROJECT — Conductor Index");
  md.push("");
  md.push("> GENERATED by the `pm` plugin — do not hand-edit. Source of truth is");
  md.push("> `.conductor/state.json` (ordering, detours, links) + OpenSpec `tasks.md` (stories).");
  md.push("> Regenerate: `/pm:status` (or `node scripts/conductor.mjs render`).");
  md.push(`> Last rendered: ${new Date().toISOString()}`);
  md.push("");

  const activeEpic = epics.find(e => e.id === state.active);
  const active = activeEpic && activeEpic.status !== "archived" ? activeEpic : null;
  md.push("## Now");
  md.push("");
  if (active) {
    md.push(`**\`${active.id}\`** — ${active.title} (${active.role}, ${active.priority}) — ${bar(active.progress)}${staleMarker(active)}`);
    if (active.reconcileNeeded) {
      md.push("");
      md.push("⚠ **Reconcile pending** — re-validate this proposal before continuing.");
    }
  } else if (activeEpic && activeEpic.status === "archived") {
    md.push(`_\`${activeEpic.id}\` was archived; the active pointer clears on next \`/pm:sync\` or commit._`);
  } else {
    md.push("_No active epic set._");
  }
  md.push("");

  md.push("## Detour stack");
  md.push("");
  if (!state.detourStack.length) {
    md.push("_Empty — no work is paused._");
  } else {
    md.push("| # | Paused epic | Reason | Detour | Reconcile on resume |");
    md.push("|---|-------------|--------|--------|---------------------|");
    state.detourStack.forEach((f, i) => {
      md.push(`| ${i + 1} | \`${f.pausedEpic}\` | ${f.reason} | \`${f.spawnedDetour || "-"}\` | ${f.reconcileOnResume ? "⚠ yes" : "no"} |`);
    });
  }
  md.push("");

  md.push("## Epics");
  md.push("");
  md.push("| Priority | Epic | Lane | Role | Status | Progress | Links |");
  md.push("|----------|------|------|------|--------|----------|-------|");
  // Render as a tree: roots in resolveEpics() order, each followed by its
  // descendants depth-first. Grouping is render-only — it does not touch the
  // resolveEpics() sort that buildBrief()/NEXT UP rely on.
  const byId = new Map(epics.map(e => [e.id, e]));
  const childrenOf = (id) => epics.filter(e => e.parent === id);
  const epicRow = (e, depth) => {
    const links = (e.links || []).filter(validLink).map(l => `${l.type}→${l.epic}`).join("; ") || "-";
    const miss = missing(e) ? " ⚠ no change on disk" : "";
    const indent = depth > 0 ? "└─ ".repeat(depth) : "";
    const kids = childrenOf(e.id);
    let progress = bar(e.progress);
    if (kids.length) {
      const archived = kids.filter(k => k.status === "archived").length;
      const rollup = `${archived}/${kids.length} children archived`;
      progress = progress === "—" ? rollup : `${rollup} · ${progress}`;
    }
    const autonomous = getAutonomy(e).level === "autonomous" ? " 🤖" : "";
    md.push(`| ${e.priority} | ${indent}\`${e.id}\` | ${e.lane} | ${e.role} | ${e.status}${e.reconcileNeeded ? " ⚠" : ""}${miss}${autonomous}${staleMarker(e)} | ${progress} | ${links} |`);
  };
  const seen = new Set();
  const emit = (e, depth) => {
    if (seen.has(e.id)) return;                 // cycle guard (validation prevents; render stays safe)
    seen.add(e.id);
    epicRow(e, depth);
    for (const c of childrenOf(e.id)) emit(c, depth + 1);
  };
  for (const e of epics) if (!e.parent || !byId.has(e.parent)) emit(e, 0);
  for (const e of epics) if (!seen.has(e.id)) emit(e, 0);   // orphaned by a cycle → render flat
  md.push("");

  md.push("## Recent detours");
  md.push("");
  try {
    const lines = fs.readFileSync(DETOURS_LOG, "utf8").trim().split("\n").filter(Boolean).slice(-8);
    if (lines.length) {
      md.push("| When | SHA | Kind | Epic | Note |");
      md.push("|------|-----|------|------|------|");
      for (const ln of lines) {
        const [when, sha, kind, epic, note] = ln.split("\t");
        md.push(`| ${when} | \`${sha}\` | ${kind} | \`${epic}\` | ${note || ""} |`);
      }
    } else { md.push("_None logged._"); }
  } catch { md.push("_None logged._"); }
  md.push("");

  md.push("## Briefing (what a fresh session sees)");
  md.push("");
  md.push("```");
  md.push(buildBrief(state));
  md.push("```");
  md.push("");

  const content = md.join("\n");
  const STAMP_RE = /^> Last rendered: .*$/m;
  let existing = "";
  try { existing = fs.readFileSync(PROJECT_MD, "utf8"); } catch { /* no file yet */ }
  writeRenderStamp();

  const flags = parseFlags(process.argv.slice(3));
  if (flags["diff-summary"]) {
    // df-project-md-diff-triviality-not-mechanically-checkable: the "Last rendered" timestamp
    // and the "Recent detours" table rotate on nearly every render even when nothing
    // epic-relevant changed, forcing manual git-diff eyeballing before a "safe to discard"
    // call. Report mechanically instead: no prior PROJECT.md at all is always epic-relevant
    // (nothing to compare against); otherwise strip both known-trivial sources of diff noise
    // before comparing.
    const epicRelevant = !existing || normalizeForDiffSummary(existing) !== normalizeForDiffSummary(content);
    process.stdout.write(`epic-relevant: ${epicRelevant ? "yes" : "no"}\n`);
  }

  if (existing && existing.replace(STAMP_RE, "") === content.replace(STAMP_RE, "")) {
    process.stderr.write("conductor: PROJECT.md unchanged (skipped rewrite)\n");
    return;
  }
  fs.writeFileSync(PROJECT_MD, content);
  process.stderr.write(`conductor: rendered ${PROJECT_MD}\n`);
}

/** Normalizes the two sources of PROJECT.md diff noise that are never "epic-relevant" on
 *  their own (per `df-project-md-diff-triviality-not-mechanically-checkable`): the
 *  "Last rendered" timestamp line (changes every render) and the "## Recent detours" table
 *  body (rotates as new entries land, oldest falls off the 8-row window). Used by
 *  `render --diff-summary` to decide whether a PROJECT.md diff is safe to mechanically
 *  discard as noise, instead of eyeballing raw diffs every time. */
export function normalizeForDiffSummary(content) {
  let out = content.replace(/^> Last rendered: .*$/m, "> Last rendered: (normalized)");
  const marker = "## Recent detours";
  const start = out.indexOf(marker);
  if (start !== -1) {
    const afterHeading = start + marker.length;
    const nextHeadingIdx = out.indexOf("\n## ", afterHeading);
    const end = nextHeadingIdx === -1 ? out.length : nextHeadingIdx;
    out = out.slice(0, afterHeading) + "\n(normalized)\n" + out.slice(end);
  }
  return out;
}

/** Records when PROJECT.md was last generated FROM the current state.json content, so
 *  `verify-state` can catch an undetected hand-edit: if state.json's mtime is newer than
 *  this stamp, someone modified it outside the render pipeline (CLAUDE.md forbids
 *  hand-editing state.json/PROJECT.md — the state of record must go through the engine's
 *  subcommands so ordering/detour-stack/link invariants stay consistent). Sidecar file
 *  (not a state.json field) so stamping never itself perturbs the content being verified. */
export function writeRenderStamp() {
  let stateMtimeMs = null;
  try { stateMtimeMs = fs.statSync(STATE_PATH).mtimeMs; } catch { /* no state.json yet */ }
  // verify-state only ever compares stateMtimeMs (see verifyState() below) — renderedAt is
  // informational only, nothing reads it back for correctness. So if state.json's mtime
  // hasn't moved since the last stamp, rewriting the file would only bump renderedAt and
  // produce a spurious byte-for-byte diff on every render() call even though nothing that
  // matters changed. Skip the rewrite in that case.
  const existing = readJSON(RENDER_STAMP_PATH, null);
  if (existing && existing.stateMtimeMs === stateMtimeMs) return;
  const stamp = { renderedAt: new Date().toISOString(), stateMtimeMs };
  fs.mkdirSync(CONDUCTOR_DIR, { recursive: true });
  fs.writeFileSync(RENDER_STAMP_PATH, JSON.stringify(stamp, null, 2) + "\n");
}
